---
name: test
on:
  push:
    branches:
      - main
      - test-windows-bug
  pull_request:
    types: [opened, synchronize]

env:
  otp-version: '26.0-rc3'
  elixir-version: 'v1.14.4'
  MIX_ENV: test

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup
        uses: starbelly/setup-beam@test-windows-bug
        with:
          otp-version: ${{ env.otp-version }}
          elixir-version: ${{ env.elixir-version }}
      - name: Erlang/OTP version (action)
        run: echo "Erlang/OTP ${{steps.setup-beam.outputs.otp-version}}"
      - name: Elixir version (action)
        run: echo "Elixir ${{steps.setup-beam.outputs.elixir-version}}"
        if: ${{matrix.combo.elixir-version}}
