---
name: test
on:
  push:
    branches:
      - main
      - test-paulos-latest-changes
  pull_request:
    types: [opened, synchronize]

env:
  otp-version: 'master'
  elixir-version: '1.14.0-otp-master'
  MIX_ENV: test

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup
        uses: paulo-ferraz-oliveira/setup-beam@feature/otp-as-master
        with:
          otp-version: ${{ env.otp-version }}
          elixir-version: ${{ env.elixir-version }}
      - name: restore-deps
        uses: actions/cache@v1
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
      - name: restore-build
        uses: actions/cache@v1
        with:
          path: _build
          key: ${{ runner.os }}-build-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
      - name: deps.get
        run: mix deps.get
      - name: compile
        run: |
          mix compile --warnings-as-errors

  dialyzer:
    needs: build
    name: Dialyzer
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup
        uses: paulo-ferraz-oliveira/setup-beam@feature/otp-as-master
        with:
          otp-version: ${{ env.otp-version }}
          elixir-version: ${{ env.elixir-version }}
      - name: restore-deps
        uses: actions/cache@v1
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
      - name: restore-build
        uses: actions/cache@v1
        with:
          path: _build
          key: ${{ runner.os }}-build-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
      - name: restore-plts
        uses: actions/cache@v1
        with:
          path: priv/plts
          key: ${{ runner.os }}-erlef-dialyzer-${{ env.otp-version }}-${{ env.elixir-version }}-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
      - name: dialyze
        run: mix dialyzer
